<div id="wrap">
    <img class="bgfade" src="<?=$this->tplMediaUrl('752', '/images/bg_1.jpg'); ?>">
    <img class="bgfade" src="<?=$this->tplMediaUrl('752', '/images/bg_2.jpg'); ?>">
    <img class="bgfade" src="<?=$this->tplMediaUrl('752', '/images/bg_3.jpg'); ?>">
</div>

<div class="row">
    <div class="large-12 medium-12 columns content">
	
		<div class="overflow">
			<nav>
				<ul>
					<li>
						<a href="#" class="hamburger"></a>
						<ul>
							<li>
								<a href="#about" class="menuAbout"><?php echo $this->basicInfoSectionTitle; ?></a>
							</li>						
							
							<li>
								<a href="#daneFirmowe"><?php echo $this->detailsDataSectionTitle; ?></a>
							</li>
							
							<li>
								<a href="#lokalizacja"><?php echo $this->mapSectionTitle; ?></a>
							</li>
						
							<li>
								<a href="#form"><?php echo $this->formSectionTitle; ?></a>
							</li>
						</ul>
					</li>
				</ul>
			</nav>

			<?php include 'partials/mainheader.phtml'; ?>

		</div><!-- overflow -->

        <div class="borderLeft">
			<div id="about"></div>
				<?php include 'partials/basicinfo.phtml'; ?>
        </div><!-- borderLeft -->

        <div class="row second">
            <div id="daneFirmowe"></div>
            <div class="large-6 medium-6 columns lineHeight borderLeft">
				<?php include 'partials/detailsdata.phtml'; ?>
            </div><!-- large-6 medium-6 columns -->

			<div class="large-6 medium-6 columns lineHeight marginTop">
				<?php include 'partials/correspondencedata.phtml'; ?>
			</div><!-- large-6 medium-6 columns -->
        </div>


        <div class="row second">
            <div id="lokalizacja"></div>
            <div class="large-6 medium-6 columns borderLeft">
				<?php include 'partials/map.phtml'; ?>
            </div><!-- large-6 medium-6 columns -->


            <div class="large-6 medium-6 columns marginTop">
                <div id="form"></div>
					<?php include 'partials/form.phtml'; ?>
                </div><!-- large-6 medium-6 columns -->
        </div>
	
    </div><!-- large 12 -->
</div><!-- row -->












	
	
	
	
