<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
    <meta charset="utf-8" />
    <base href="/">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
	    <link rel="icon" href="<?=$this->tplMediaUrl('1008', '/images/fav.ico'); ?>" type="image/x-icon" />
		<link rel="shortcut icon" href="<?=$this->tplMediaUrl('1008', '/images/fav.ico'); ?>" type="image/x-icon" />
    <title><?php echo $this->businessCardTitle; ?></title>
	
	
	
	<script src="<?=$this->baseUrl('common/js/jquery-2.1.3.js'); ?>" type="text/javascript"></script>
	<link rel="stylesheet" href="<?=$this->tplMediaUrl('1008', '/style/foundation.css'); ?>" />
	<link rel="stylesheet" href="<?=$this->tplMediaUrl('1008', '/style/reset.css'); ?>" />
	<link rel="stylesheet" href="<?=$this->baseUrl('common/css/font-Lato-Light.css'); ?>" />	
	<link rel="stylesheet" href="<?=$this->tplMediaUrl('1008', '/style/foundation.min.css'); ?>" />
	
	<link rel="stylesheet" href="<?=$this->tplMediaUrl('1008', '/style/wiz.css'); ?>" />
	<script src="<?=$this->tplMediaUrl('1008', '/js/modernizr.custom.js'); ?>" type="text/javascript"></script>


	



	
	
</head>
<body>

<?php
    $templateVersion = 4;
    if ($this->mapEnable && $this->formEnable && !$this->offerEnable) {      
        $templateVersion = 1; // InfoPodstawowe + mapa + formularz
    } 
	elseif ($this->mapEnable && !$this->formEnable && !$this->offerEnable) { 
        $templateVersion = 2;  // InfoPodstawowe + mapa
    } 
	
	
	elseif (!$this->mapEnable && $this->formEnable && !$this->offerEnable) { 
        $templateVersion = 3; // InfoPodstawowe + formularz
    } 
	
	elseif (!$this->mapEnable && !$this->formEnable && $this->offerEnable) { 
        $templateVersion = 6; // InfoPodstawowe + oferta
    } 
	
	elseif (!$this->mapEnable && $this->formEnable && $this->offerEnable) { 
        $templateVersion = 7; // InfoPodstawowe + formularz + oferta
    } 
	
	elseif ($this->mapEnable && !$this->formEnable && $this->offerEnable) { 
        $templateVersion = 8; // InfoPodstawowe + mapa + oferta
    } 
	
	elseif ($this->mapEnable && $this->formEnable && $this->offerEnable) { 
        $templateVersion = 5; // InfoPodstawowe + mapa + formularz + oferta
	} else {                                          
        $templateVersion = 4;
    }
?>

<?php
	include 'version'.$templateVersion.'.phtml'; 

?> 

<script src="<?=$this->tplMediaUrl('1008', '/js/libs.min.js'); ?>" type="text/javascript"></script>
<script src="<?=$this->tplMediaUrl('1008', '/js/custom.js'); ?>" type="text/javascript"></script>


</body>
</html>


