<?php if($this->formEnable) : ?>



        <?php if ($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>

            <h2>Dziękujemy za przesłanie wiadomości!</h2>

				<script>
                    $(document).ready(function() {
						var offsetScroll = -50; //Offset of 20px
						$("html, body").animate({
							scrollTop: $('#formularz').offset().top + offsetScroll
						}, 1);
                    });
                </script>
				
				
        <?php endif ?>

        <?php if ($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>

            <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
			
                  <script>
                        $(document).ready(function() {
							var offsetScroll = -50; //Offset of 20px
							  $("html, body").animate({
								scrollTop: $('#formularz').offset().top + offsetScroll
							}, 1);
                        });
                    </script>
					
            <?php endif; ?>
			
			<div id="formularz">
			    <!-- formularz -->
                <div class="blockContent contFormula">
                    <p class="header_column"><?php echo $this->formSectionTitle; ?></p>
                    <hr class="headerLine" />
                    <form action="<?=$this->contactForm->getAction()?>" method="<?=$this->contactForm->getMethod();?>" class="form">

                    <div class="large-6 medium-6 columns paddingLeftNone">
                        <?php echo $this->contactForm->email->renderViewHelper();?>
						<?php echo $this->contactForm->email->renderErrors()?>
                    </div><!-- large-6 medium-6 columns -->

                    <div class="large-6 medium-6 columns paddingLeftNone">
                        <?php echo $this->contactForm->phone->renderViewHelper();?>
						<?php echo $this->contactForm->phone->renderErrors()?>
                    </div><!-- large-6 medium-6 columns -->

                    <div class="large-12 columns paddingLeftNone">
                        <?php echo $this->contactForm->subject->renderViewHelper();?>
						<?php echo $this->contactForm->subject->renderErrors()?>
                    </div><!-- large-12 columns -->

                    <div class="large-12 columns paddingLeftNone">
                        <?php echo $this->contactForm->message->renderViewHelper();?>
						<?php echo $this->contactForm->message->renderErrors()?>
                    </div><!-- large-12 columns -->

                    <div class="pnlSend">

						<div class="large-12 medium-12 columns" style="padding-left: 0;">
								
							<div class="pull-left">
								<div id="captchaContainer" class="left">
									<?php echo $this->contactForm->captcha->render()?>
								</div>
							</div>

							<div class="right">
								<?php echo $this->contactForm->send->renderViewHelper();?>
							</div>
							
						</div><!-- large-12 medium-12 columns -->

                    </div> <!-- pnlSend -->

                    </form>
                </div><!-- blockContent -->
            </div><!-- formularz -->
			

        <?php endif; ?>

<?php endif; ?>


