<?php if($this->mapEnable) : ?>

<a href="#lokalizacja" class="strzalka_nieb_pom allLink"></a>
<div id="lokalizacja">

    <div class="row">
        <div class="large-12 columns fullSize">
            <p class="header_column"><?php echo $this->mapSectionTitle; ?></p>
            <hr class="headerLine paddingLeft" />
        </div><!-- large-12 columns -->
    </div><!-- row -->

    <div class="maps">

        <?php include "./common/templates/mapframestrategy.phtml"; ?>

    </div><!-- maps -->

    <?php endif; ?>





