    <style>
        .contentSlider {
            width: 680px;
        }
    </style>
	
<div class="row">
	<div class="large-12 columns bg">
		<div class="panel">
			<?php include 'partials/mainheader.phtml'; ?>
			
			
			<div class="slider">
				<div class="step">
					<?php include 'partials/basicinfo.phtml'; ?>
				</div><!-- step -->
				
				<div class="step">
					<?php include 'partials/detailsdata.phtml'; ?>
				</div><!-- step -->
			
				<div class="step">
					<?php include 'partials/correspondencedata.phtml'; ?>
				</div><!-- step -->
				
			</div><!-- slider -->
			
		</div><!-- panel -->
	</div><!-- large-12 columns bg -->
</div><!-- row -->
