	<div id="mobile-navigation" style="height: 40px;">
		<div class="burger"></div>
		<div class="menu-list">
			<ul class="menuSocial">
			<?php if($this->socialMediaEnable) : ?>
                <li>
					<?php if($this->socialMediaFacebookEnable) : ?>
						<a href="<?php echo $this->socialMediaFacebookUrl; ?>" class="facebook" target="_blank">facebook</a>
					<?php endif; ?>
				</li>
				
				<li>
					<?php if($this->socialMediaInstagramEnable) : ?>
						<a href="<?php echo $this->socialMediaInstagramUrl; ?>" class="instagram" target="_blank">instagram</a>
					<?php endif; ?>
				</li>
				
				<li>
					<?php if($this->socialMediaTwitterEnable) : ?>
						<a href="<?php echo $this->socialMediaTwitterUrl; ?>" class="twitter" target="_blank">twitter</a>
					<?php endif; ?>
				</li>
				
				<li>
					<?php if($this->socialMediaLinkedInEnable) : ?>
						<a href="<?php echo $this->socialMediaLinkedInUrl; ?>" class="linkedIn" target="_blank">linkedin</a>
					<?php endif; ?>
				</li>
				
				<li>
					<?php if($this->socialMediaGooglePlusEnable) : ?>
						<a href="<?php echo $this->socialMediaGooglePlusUrl; ?>" class="google_plus" target="_blank">google plus</a>
					<?php endif; ?>
				</li>
				
				<li>
					<?php if($this->socialMediaYouTubeEnable) : ?>
						<a href="<?php echo $this->socialMediaYouTubeUrl; ?>" class="youTube" target="_blank">youtube</a>
					<?php endif; ?>
				</li>
            </ul>
			<?php endif; ?>
		
			<ul class="menuHeader">
				<li><a class="linkToSection" data-link="1" href="<?=$this->baseUrl('#'); ?>"><?php echo $this->basicInfoSectionTitle; ?></a></li>
				<li><a class="linkToSection" data-link="2" href="<?=$this->baseUrl('#'); ?>"><?php echo $this->detailsDataSectionTitle; ?></a></li>
				<li></li>
				<li></li>
				<li><a class="linkToSection" data-link="5" href="<?=$this->baseUrl('#'); ?>"><?php echo $this->formSectionTitle; ?></a></li>
			</ul>
		</div>
	</div><!-- mobile-navigation -->


    <div class="row">
        <div class="large-12 columns noPaddingRight noPaddingLeft">
            <div class="panel">
                <div class="large-2 medium-3 small-12 columns navigation navblock">
                    <ul class="menuHeader">
                        <li><a href="<?=$this->baseUrl('#'); ?>" data-link="1" class="linkToSection current"><?php echo $this->basicInfoSectionTitle; ?></a></li>
                        <li><a href="<?=$this->baseUrl('#'); ?>" data-link="2" class="linkToSection"><?php echo $this->detailsDataSectionTitle; ?></a></li>
						<li></li>
                        <li></li>
                        <li><a href="<?=$this->baseUrl('#'); ?>" data-link="5" class="linkToSection formLink"><?php echo $this->formSectionTitle; ?></a></li>
                    </ul>
<?php if($this->socialMediaEnable) : ?>
                    <ul class="menuSocial">
                       <li>
							<?php if($this->socialMediaFacebookEnable) : ?>
								<a href="<?php echo $this->socialMediaFacebookUrl; ?>" class="facebook" target="_blank">facebook</a>
							<?php endif; ?>
						</li>
						
						<li>
							<?php if($this->socialMediaInstagramEnable) : ?>
								<a href="<?php echo $this->socialMediaInstagramUrl; ?>" class="instagram" target="_blank">instagram</a>
							<?php endif; ?>
						</li>
						
						<li>
							<?php if($this->socialMediaTwitterEnable) : ?>
								<a href="<?php echo $this->socialMediaTwitterUrl; ?>" class="twitter" target="_blank">twitter</a>
							<?php endif; ?>
						</li>
						
						<li>
							<?php if($this->socialMediaLinkedInEnable) : ?>
								<a href="<?php echo $this->socialMediaLinkedInUrl; ?>" class="linkedIn" target="_blank">linkedin</a>
							<?php endif; ?>
						</li>
						
						<li>
							<?php if($this->socialMediaGooglePlusEnable) : ?>
								<a href="<?php echo $this->socialMediaGooglePlusUrl; ?>" class="google_plus" target="_blank">google plus</a>
							<?php endif; ?>
						</li>
						
						<li>
							<?php if($this->socialMediaYouTubeEnable) : ?>
								<a href="<?php echo $this->socialMediaYouTubeUrl; ?>" class="youTube" target="_blank">youtube</a>
							<?php endif; ?>
						</li>
                    </ul>
					<?php endif; ?>
                </div><!-- large-4 medium-6 columns -->	
				
				
				
				<div class="large-10 medium-9 columns noPaddingRight noPaddingLeft">
					<section class="sect_oNas active" data-target="1">
						
							<?php include 'partials/mainheader.phtml'; ?>
							<?php include 'partials/basicinfo.phtml'; ?>
						
						<a href="<?=$this->baseUrl('#'); ?>" data-link="2" class="linkToSection"><span>IDŹ W DÓŁ</span></a>
					</section>
				
					<section class="sect_daneKontaktowe" data-target="2">
						
							<?php include 'partials/mainheader.phtml'; ?>
						
							<?php include 'partials/detailsdata.phtml'; ?>
							<?php include 'partials/correspondencedata.phtml'; ?>
						
                        <a href="<?=$this->baseUrl('#'); ?>" data-link="5" class="linkToSection"><span>IDŹ W DÓŁ</span></a>
                    </section>

				
					<section class="sect_formularzKontaktowy" data-target="5">
						
							<?php include 'partials/mainheader.phtml'; ?>
					
							<?php include 'partials/form.phtml'; ?>
						
						<a href="<?=$this->baseUrl('#'); ?>" data-link="1" class="linkToSection last"><span>IDŹ W GÓRĘ</span></a>
                    </section>
				
				</div><!-- large-6 medium-6 columns -->
			</div><!-- panel -->
        </div><!-- large-12 columns -->
    </div><!-- row -->


	
