<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
    <meta charset="utf-8" />
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><?php echo $this->businessCardTitle; ?></title>

    <link rel="stylesheet" href="<?=$this->baseUrl('common/css/foundation.css'); ?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('common/css/reset.css');?>" />

    <link rel="stylesheet" href="<?=$this->baseUrl('common/css/font-Lato-Light.css'); ?>" />
    <link rel="stylesheet" href="<?=$this->tplMediaUrl('288', '/style/wiz1-full.css'); ?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('common/css/jquery.fancybox-1.3.4.css'); ?>" />

    <link rel="icon" href="<?=$this->tplMediaUrl('288', '/favicon.ico'); ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?=$this->tplMediaUrl('288', '/favicon.ico'); ?>" type="image/x-icon" />

    <script src="<?=$this->baseUrl('common/js/jquery-1.4.3.min.js'); ?>" type="text/javascript"></script>
    <script src="<?=$this->baseUrl('common/js/jquery.fancybox-1.3.4.js'); ?>" type="text/javascript"></script>
    <script src="<?=$this->baseUrl('common/js/jquery.foggy.min.js'); ?>" type="text/javascript"></script>
    <script src="<?=$this->tplMediaUrl('288', '/js/wiz.js'); ?>" type="text/javascript"></script>

</head>
<body>

<?php
    $templateVersion = 4;
    if ($this->mapEnable && $this->formEnable && !$this->offerEnable) {      
        $templateVersion = 1; // InfoPodstawowe + mapa + formularz
    } 
	elseif ($this->mapEnable && !$this->formEnable && !$this->offerEnable) { 
        $templateVersion = 2;  // InfoPodstawowe + mapa
    } 
	
	
	elseif (!$this->mapEnable && $this->formEnable && !$this->offerEnable) { 
        $templateVersion = 3; // InfoPodstawowe + formularz
    } 
	
	elseif (!$this->mapEnable && !$this->formEnable && $this->offerEnable) { 
        $templateVersion = 6; // InfoPodstawowe + oferta
    } 
	
	elseif (!$this->mapEnable && $this->formEnable && $this->offerEnable) { 
        $templateVersion = 7; // InfoPodstawowe + formularz + oferta
    } 
	
	elseif ($this->mapEnable && !$this->formEnable && $this->offerEnable) { 
        $templateVersion = 8; // InfoPodstawowe + mapa + oferta
    } 
	
	elseif ($this->mapEnable && $this->formEnable && $this->offerEnable) { 
        $templateVersion = 5; // InfoPodstawowe + mapa + formularz + oferta
	} else {                                          
        $templateVersion = 4;
    }
?>

<?php
   include 'version'.$templateVersion.'.phtml';

	
?>

</body>
</html>