<img src="<?=$this->tplMediaUrl('288', '/images/bg.png'); ?>" class="all">
<div class="row" style="padding-bottom: 2em;">
    <div class="large-12 columns steel bg">
        <div class="panel">
            <?php include 'partials/mainheader.phtml'; ?>
            <div class="row">
                <div class="large-8 medium-8 columns">

                    <?php include 'partials/basicinfo.phtml'; ?>

                    <hr class="redLine_default" />

                    <?php include 'partials/detailsdata.phtml'; ?>

                    <div class="link_container">

                        <?php include 'partials/correspondencedata.phtml'; ?>

                    </div><!-- link_container -->

                </div><!-- large-8 medium-8 columns -->


                <div class="large-4 medium-4 columns">
                    <hr class="redLine" />
                    <?php include 'partials/map.phtml'; ?>
                </div>

            </div><!-- row -->

        </div>
    </div> <!-- large-12 columns -->
</div>
