<img src="<?=$this->tplMediaUrl('288', '/images/bg.png'); ?>" class="all">
<div class="row" style="padding-bottom: 2em;">
    <div class="large-12 columns steel bg">
        <div class="panel">
            <?php include 'partials/mainheader.phtml'; ?>
            <div class="row">
                <div class="large-5 medium-5 columns" style="margin-top: 50px;">

                    <?php include 'partials/basicinfo.phtml'; ?>

                </div><!-- large-5 medium-5 columns -->


                <div class="large-7 medium-7 columns" style="margin-top: 50px;">

                    <?php include 'partials/detailsdata.phtml'; ?>

                    <div class="link_container">

                        <?php include 'partials/correspondencedata.phtml'; ?>

                    </div><!-- link_container -->

                </div>

            </div><!-- row -->

        </div>
    </div> <!-- large-12 columns -->
</div>
