<div id="section-1" class="section-wrapper">

	<!-- Menu.Begin -->
	<div class="row menu_top" >
		<div class="medium-12 large-12 small-12 columns" >
			<div class="rmm">
				<ul id="nav">
					<li class="current"><a href='#section-1' target="_self"><?php echo $this->basicInfoSectionTitle; ?></a></li>
					<li><a href='#section-2' target="_self"><?php echo $this->detailsDataSectionTitle; ?></a></li>
					<li><a href='#section-3' target="_self"><?php echo $this->offerSectionTitle; ?></a></li>
					<li><a href='#section-4' target="_self"><?php echo $this->formSectionTitle; ?></a></li>
					<li><a href='#section-5' target="_self"><?php echo $this->mapSectionTitle; ?></a></li>
				</ul>
			</div>
		</div>
	</div>	
	<!-- Menu.End-->
	
	<!-- Top.Begin -->
	<div class="row">

			<?php include 'partials/mainheader.phtml'; ?>	
			
	
			<?php include 'partials/basicinfo.phtml'; ?>

	</div>
</div>


<!-- Section2.Begin -->				
<div id="section-2" class="section-wrapper">
<img src="<?=$this->tplMediaUrl('992', '/images/koperta_opt.jpg'); ?>">	


					<?php include 'partials/detailsdata.phtml'; ?>
				

	
	
		<?php include 'partials/correspondencedata.phtml'; ?>


</div>

</div>
</div>
<!-- Section2.End -->	

<div id="section-3" class="section-wrapper">
			<?php include 'partials/offerdata.phtml'; ?>
	
</div>








<div id="section-4" class="section-wrapper">

	<img class="olowek" src="<?=$this->tplMediaUrl('992', '/images/olowek_opt.jpg'); ?>">
	<div class="row">
		<div class="medium-12 large-12 small-12 columns">
		<?php include 'partials/form.phtml'; ?>
		</div>
	</div>



	
</div>


<div id="section-5" class="section-wrapper">
<div class="row">
    <h2><?php echo $this->mapSectionTitle; ?></h2>
		<div class="medium-12 large-12 small-12 columns">

</div>
</div>
	<div class="maps">

		<div id="googleMap"><?php include 'partials/map.phtml'; ?></div>
	</div>																								
</div>


<div id="section-6" class="section-wrapper">
	<div class="row">
		<div class="medium-12 large-12 small-12 columns">
	
		</div>
	</div>
</div>





	
