<?php if($this->detailsDataEnable) : ?>
<div class="card data">
	
	<?php if($this->detailsDataAddressEnable) : ?>
	 
		<p><strong>Adres:</strong><br>
                        <?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?><br>
                        <?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?></p>
<?php endif; ?>
                   
				<?php if($this->detailsDataPhoneEnable) : ?>
					 <p><strong>Tel.:</strong> <?php echo $this->detailsDataPhoneValue; ?><br>
				<?php endif; ?>
				
				<?php if($this->detailsDataEmailEnable) : ?>
					<strong>E-mail:</strong> <a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a><br>
				<?php endif; ?>
				
				<?php if($this->detailsDataNipEnable) : ?>
					<strong>NIP:</strong> <?php echo $this->detailsDataNipValue; ?>
				<?php endif; ?>
				</p>

				<?php if($this->detailsDataLinkEnable) : ?>
						<li class="info"><span class="icon"></span><strong>Adres WWW: </strong><a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?></a></li>
				<?php endif; ?>
				
				</div>
	
			
<?php endif; ?>



