<?php if($this->formEnable) : ?>

        <?php if ($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>

            <h2>Dziękujemy za przesłanie wiadomości!</h2>

            <script>
                 $(document).ready(function() {
							var offsetScroll = -5; //Offset of 20px
							  $("html, body").animate({
								scrollTop: $('#contact').offset().top + offsetScroll
							}, 1);
                        });
            </script>
        <?php endif ?>

        <?php if ($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>

            <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
                  <script>
						$(document).ready(function() {
							var offsetScroll = -5; //Offset of 20px
							  $("html, body").animate({
								scrollTop: $('#contact').offset().top + offsetScroll
							}, 1);
                        });
                    </script>
            <?php endif; ?>

			<div class="small-12 medium-4 large-5 columns">
                <h2><?php echo $this->formSectionTitle; ?></h2>
            </div>

				<form action="<?=$this->contactForm->getAction()?>" method="<?=$this->contactForm->getMethod();?>">
					<div class="small-12 medium-8 large-6 large-offset-1 end columns">
							<div class="row">
								<div class="medium-12 large-6 columns">
									<?php echo $this->contactForm->email->renderViewHelper();?>
									<?php echo $this->contactForm->email->renderErrors()?>
								</div>
								<div class="medium-12 large-6 end columns">
									<?php echo $this->contactForm->phone->renderViewHelper();?>
									<?php echo $this->contactForm->phone->renderErrors()?>
								</div>
							</div>
						
							<div class="row">
								<div class="medium-12 columns">
									<?php echo $this->contactForm->subject->renderViewHelper();?>
									<?php echo $this->contactForm->subject->renderErrors()?>
								</div>
							</div>

							<div class="row">
								<div class="medium-12 columns">
									<?php echo $this->contactForm->message->renderViewHelper();?>
									<?php echo $this->contactForm->message->renderErrors()?>
								</div>
							</div>
						
							<div class="row">
								<div class="small-12 medium-5 large-4 columns captcha">
									<?php echo $this->contactForm->captcha->render()?>
								</div>
							</div>
							
							<div class="row">
								<div class="small-12 columns">
									<?php echo $this->contactForm->send->renderViewHelper();?>
								</div>
							</div>
					</form>
				</div>

        <?php endif; ?>

<?php endif; ?>






