<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8" />
    <title>Błąd 404</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #F5F5F5;
        }

        #containerMain {
            margin: 30px auto;
            width: 1000px;
        }

        hr.vertical {
            border-top: 1px solid #DADADA;
            border-right: none;
            border-bottom: 1px solid #FFFCFC;
            border-left: none;
        }

        #containerMain .main  img{
            /* margin: 100px 0 0 43%; */
        }

        .header img {
            border: none;
        }

        p span.button a {
            background: url("<?=$this->baseUrl('/images/arrowsRight.png')?>") no-repeat scroll right 5px transparent;
            display: block;
            color: #3E86C8;
            text-transform: none;
            text-decoration: none;
            font-weight: normal;
            font-size: 12px;
        }

        p span.button {
            background: url("<?=$this->baseUrl('/images/buttonCompare.png')?>") repeat-x scroll 0 0 transparent;
            border: 1px solid #D6D6D6;
            display: block;
            padding: 5px 18px;
            margin: 20px auto;
            width: 140px;
        }

        #containerMain .main p {
            text-align: center;
        }

        #containerMain .main p {
            color: #B2B2B2;
            font-weight: bold;
            margin-bottom: 100px;
            text-transform: uppercase;
            font-size: 26px;
            font-family: Arial, sans-serif;
            margin-top: 10px;
        }

        #containerMain .main p span {
            font-size: 15px;
            line-height: 15px;
        }

        #containerMain .main p span.newLine {
            display: block;
        }

        #containerMain .footer {
            font-family: Arial, sans-serif;
            width: 1000px;
        }

        #containerMain .footer p.copy {
            float: left;
            color: #777777;
            text-shadow: 1px 1px 0 #FFFFFF;
            font-size: 12px;
            font-family: Arial, sans-serif;
        }

        .main {
            border: 1px solid #dadada;
            margin: 30px 0 40px;
            overflow: hidden;
        }

        .step {
            float: left;
        }

        .v1 {
            width: 400px;
        }

        .v1 img {
            margin: 90px 0 0 135px;
        }

        .v2 {

        }

        .footer .footer-help {
            border-bottom: 1px solid #FFFCFC;
            margin: 0 0 10px;
        }

        .footer .footer-help .inner {
            border-bottom: 1px solid #DADADA;
            border-top: 1px solid #FFFCFC;
            height: 31px !important;
            padding: 12px 0 14px;
            overflow: hidden;
        }

        .footer .footer-help p.header {
            float: left;
            font-family: Arial, sans-serif;
            font-size: 20px;
            font-weight: bold;
            padding-left: 135px;
            line-height: 0px;
            margin: 0;
            line-height: 31px;
            color: black;
        }

        .footer a {
            color: #777777;
            text-decoration: none;
        }

        .footer {
            border-top: 1px solid #DADADA;
            color: #777777;
            margin: 12px auto 0;
            padding: 0 0 30px;
            text-shadow: 1px 1px 0 #FFFFFF;
            width: 1000px;
        }

        .footer .footer-help p.phone span {
            font-size: 16px;
        }

        .footer .footer-help p.phone {
            background: url("<?=$this->baseUrl('/images/footer-service_phone.png')?>") no-repeat scroll 0 50% transparent;
            padding-left: 27px;
            line-height: 31px;
            margin: 0 0 0 42px;
        }

        .footer .footer-help p {
            float: left;
            font-size: 14px;
            font-weight: bold;
            height: 31px !important;
            margin-left: 42px;
        }

        .footer .footer-help p.e-mail {
            background: url("<?=$this->baseUrl('/images/footer-service_email.png')?>") no-repeat scroll 0 50% transparent;
            margin-top: 2px;
            padding-left: 45px;
            line-height: 25px;
        }

        .footer .footer-help p.chat {
            background: url("<?=$this->baseUrl('/images/foter-service_chat.png')?>") no-repeat scroll 0 50% transparent;
            margin-top: 2px;
            padding-left: 45px;
            line-height: 25px;
        }

        .footer {
            color: #777777;
            text-shadow: 1px 1px 0 #FFFFFF;
        }

    </style>


</head>
<body>
<div id="containerMain">
    <div class="header">
        <a href="http://nazwa.pl" title="nazwa.pl"><img src="<?= $this->baseUrl("/images/logo.png")?>" alt="nazwa.pl logo" /></a>
    </div><!-- header -->
    <div class="main">
        <div class="step v1">
            <img src="<?=$this->baseUrl("/images/404.png")?>" alt="blokada"/>
            <p>
                Błąd 404<br />
                <span>Skontaktuj się <span class="newLine">z działem obsługi klienta</span></span>

					<span class="button">
						<a href="<?=$this->baseUrl('/');?>">
                            Przejdź do wizytówki
                        </a>
					</span><!-- button -->
            </p>
        </div><!-- step -->

        <div class="step v2">
            <img src="<?=$this->baseUrl("/images/reka_404.png")?>" alt="blokada" />
        </div><!-- step -->
    </div><!-- main -->
    <div class="footer">
        <div class="footer-help">
            <div class="inner">
                <p class="header">Potrzebujesz pomocy?</p>
                <p class="phone"><span>801 33 22 33</span> 12 297 88 10</p>
                <p class="e-mail"><a href="mailto:kontakt@nazwa.pl">kontakt@nazwa.pl</a></p>
            </div><!-- inner -->
        </div><!-- footer-help -->
        <p class="copy">&copy; <span id="year">2015</span> nazwa.pl. Wszelkie prawa zastrzeżone</p><!-- copy -->
    </div><!-- footer -->
</div><!-- containerMain -->
<script>
    datestring = new Date().getFullYear()
    document.getElementById('year').innerHTML = datestring;
</script>

<?php if (isset($this->exception)): ?>
    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>
    <h3>Exception information:</h3>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

<?php endif ?>

</body>
</html>


