<?php if($this->correspondenceDataEnable) : ?>
   
      <!--  <?php echo $this->correspondenceDataSectionTitle; ?> -->
			<div class="small-12 medium-6 large-4 large-offset-2 columns">
                <h2><?php echo $this->correspondenceDataSectionTitle; ?></h2>
            </div>
    
            
            <div class="small-12 medium-6 large-4 end columns">
                <ul class="no-bullet company-data">   
					<?php if($this->correspondenceDataAddressEnable) : ?>
                    <li class="address"><span class="icon"></span><strong>Adres:</strong>
           
						<br><?php echo $this->correspondenceDataAddressStreet; ?> <?php echo $this->correspondenceDataAddressLocalNumber; ?>
						<br><?php echo $this->correspondenceDataAddressZipCode; ?> <?php echo $this->correspondenceDataAddressCity; ?>
								 
					<?php endif; ?>

					<?php if($this->correspondenceDataPhoneEnable) : ?>
						<li class="phone"><span class="icon"></span><strong>Tel.:</strong> <?php echo $this->correspondenceDataPhoneValue; ?></li>
					<?php endif; ?>
					
<?php endif; ?>
				</ul>
            </div>


