<?php if($this->detailsDataEnable) : ?>
	
	<div class="small-12 medium-6 large-4 large-offset-2 columns">
        <h2><?php echo $this->detailsDataSectionTitle; ?></h2>
    </div>
	
	
		
		<div class="small-12 medium-6 large-4 end columns">
			<ul class="no-bullet company-data">
			<?php if($this->detailsDataAddressEnable) : ?>
				<li class="address"><span class="icon"></span><strong>Adres:</strong>
                        <br><?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?>
                        <br><?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?></li>
			<?php endif; ?>
				<li class="phone">
							<?php if($this->detailsDataPhoneEnable) : ?>
								<span class="icon"></span><strong>Tel.:</strong> <?php echo $this->detailsDataPhoneValue; ?></p>
							<?php endif; ?>
				</li>
				
					

					<?php if($this->detailsDataEmailEnable) : ?>
						<li class="email"><span class="icon"></span><strong>E-mail:</strong> <a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a></li>
					<?php endif; ?>

					<?php if($this->detailsDataNipEnable) : ?>
					
						<li class="info"><span class="icon"></span><strong>NIP:</strong> <?php echo $this->detailsDataNipValue; ?></li>
					
					<?php endif; ?>

					<?php if($this->detailsDataLinkEnable) : ?>
						<li class="info"><span class="icon side"></span><strong>Adres WWW:&nbsp;</strong><a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?></a></li>
					<?php endif; ?>
				
			</ul>
		</div>	




	<?php endif; ?>