<?php if($this->correspondenceDataEnable) : ?>
   
      <!--  <?php echo $this->correspondenceDataSectionTitle; ?> -->


    <!-- warstwa adres do korespondencji -->
   
        <p class="header_column"><?php echo $this->correspondenceDataSectionTitle; ?></p>

            <p class="Adress">
                <span class="name1"><?php echo $this->businessCardTitle; ?></span>
            </p>
                        
            <?php if($this->correspondenceDataAddressEnable) : ?>
                         
            <p class="Adress">
                <?php echo $this->correspondenceDataAddressStreet; ?> <?php echo $this->correspondenceDataAddressLocalNumber; ?>
            </p>
                         
            <p class="Phone">
                <span class="name3"><?php echo $this->correspondenceDataAddressZipCode; ?> <?php echo $this->correspondenceDataAddressCity; ?></span>
            </p>
                         
            <?php endif; ?>

            <?php if($this->correspondenceDataPhoneEnable) : ?>
                         
                  <p class="Phone"><span class="name3">Tel:</span> <?php echo $this->correspondenceDataPhoneValue; ?></p>
                         
            <?php endif; ?>

<?php endif; ?>

