	
	<header>
        <div class="row">
            <div class="small-12 columns contain-to-grid fixed">
                <nav class="top-bar" data-topbar role="navigation" data-options="scrolltop: false">
                    <ul class="title-area">
                        <li class="name"></li>
                        <li class="toggle-topbar menu-icon"><a href="<?=$this->baseUrl('#'); ?>"><span></span></a></li>
                    </ul>
                    <div class="section top-bar-section">
                        <ul id="main-menu" class="left">
                            <li><a href="<?=$this->baseUrl('#'); ?>" id="menu-start" class="active">Start</a></li>
                            <li><a href="<?=$this->baseUrl('#'); ?>" id="menu-about"><?php echo $this->basicInfoSectionTitle; ?></a></li>
                            <li><a href="<?=$this->baseUrl('#'); ?>" id="menu-info"><?php echo $this->detailsDataSectionTitle; ?></a></li>
                            <li><a href="<?=$this->baseUrl('#'); ?>" id="menu-map" class="mapInvoker"><?php echo $this->mapSectionTitle; ?></a></li>
                            <li><a href="<?=$this->baseUrl('#'); ?>" id="menu-contact"><?php echo $this->formSectionTitle; ?></a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>

	
	<div class="content-wrapper">
	
	    <div id="start" class="section content-section">
            <div class="row">
                <div class="small-12 columns text-center">
                    <canvas id="canvas-stars"></canvas>
                    <?php include 'partials/mainheader.phtml'; ?>
                </div>
            </div>
        </div>
	
	
	
	
		<div id="about" class="section content-section">
			<div class="row">
				<div class="content-wrapper small-12 medium-10 medium-offset-1 large-8 large-offset-2 end columns">
					<div class="row">
						 <div class="small-12 end columns">
							<?php include 'partials/basicinfo.phtml'; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		
		<div id="info" class="section content-section">
            <div class="row">
				<div class="content-wrapper small-12 medium-10 medium-offset-1 large-8 large-offset-2 end columns">
					<div class="row">
						<?php include 'partials/detailsdata.phtml'; ?>
						<div class="small-12 medium-6 end columns"></div>
					</div>
					
					<div class="row">
						<?php include 'partials/correspondencedata.phtml'; ?>
					</div>
				</div>
			</div>
		</div>
		
		
		<div id="map" class="section content-section">
            <div class="row">
				<div class="content-wrapper small-12 medium-10 medium-offset-1 large-8 large-offset-2 end columns">
					<div class="row">
                        <div class="small-12 end columns">
							<?php include 'partials/map.phtml'; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div id="contact" class="section content-section">
            <div class="row">
				<div class="content-wrapper small-12 medium-10 medium-offset-1 large-8 large-offset-2 end columns"> 
					<div class="row">
                        <div class="small-12 end columns">
							<?php include 'partials/form.phtml'; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	
	</div><!-- content-wrapper -->
	
	
	
    
    <footer>
        
    </footer>
	
	
    <script src="<?=$this->tplMediaUrl('1098', '/js/jsmore/libs.min.js'); ?>"></script>
	<script src="<?=$this->tplMediaUrl('1098', '/js/foundation.min.js'); ?>"></script>
    <script src="<?=$this->tplMediaUrl('1098', '/js/custom.js'); ?>"></script>
	<script>
        $(document).foundation();
    </script>
	
	
