<?php if($this->correspondenceDataEnable) : ?>
   
	<div class="small-12 medium-12"> <!-- zmiana -->
        <h2 style="margin-left: 1rem;"><?php echo $this->correspondenceDataSectionTitle; ?></h2>
    </div>
   
    
            <?php if($this->correspondenceDataAddressEnable) : ?>
				<div class="small-12 medium-6 columns"> <!-- zmiana -->
                    <p class="company-data address">
                        <span class="icon"></span>
                        <strong>Adres:</strong><br>
                        <?php echo $this->businessCardTitle; ?><br>
                        <?php echo $this->correspondenceDataAddressStreet; ?> <?php echo $this->correspondenceDataAddressLocalNumber; ?><br>
                        <?php echo $this->correspondenceDataAddressZipCode; ?> <?php echo $this->correspondenceDataAddressCity; ?></p>
                </div>
			
			<?php endif; ?>
			
			
				<?php if($this->correspondenceDataPhoneEnable) : ?>
<div class="small-12 medium-6 columns"> 
					<p class="company-data contact">
						<span class="icon"></span>
						<strong>Tel.:</strong> <?php echo $this->correspondenceDataPhoneValue; ?></p>
					</p>
  </div>
				<?php endif; ?>
          


<?php endif; ?>
