<?php if($this->formEnable) : ?>


  

        <?php if ($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>

            <h2>Dziękujemy za przesłanie wiadomości!</h2>

            <script>
                $(document).ready(function() {
                    $('#main-menu a').removeClass('active');
		$('#main-menu a #menu-contact').addClass('active');

		$('.content-section').hide().removeClass('animated bounceInLeft');
		
		$('#contact').show().addClass('animated bounceInLeft');
                });
            </script>
        <?php endif ?>

        <?php if ($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>

            <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
                  <script>
                        $(document).ready(function() {
                            $('#main-menu a').removeClass('active');
		$('#main-menu a #menu-contact').addClass('active');

		$('.content-section').hide().removeClass('animated bounceInLeft');
		
		$('#contact').show().addClass('animated bounceInLeft');
                        });
                    </script>
            <?php endif; ?>
			

			
			
			<h2><?php echo $this->formSectionTitle; ?></h2>
			

            <form action="<?=$this->contactForm->getAction()?>" method="<?=$this->contactForm->getMethod();?>">
                
					<div class="row">
                        <div class="medium-6 columns">
                            <?php echo $this->contactForm->email->renderViewHelper();?>
							<?php echo $this->contactForm->email->renderErrors()?>
                        </div>
                        <div class="medium-6 end columns">
                            <?php echo $this->contactForm->phone->renderViewHelper();?>
							<?php echo $this->contactForm->phone->renderErrors()?>
                        </div>
                    </div>
				
					<div class="row">
                        <div class="medium-12 columns">
                            <?php echo $this->contactForm->subject->renderViewHelper();?>
							<?php echo $this->contactForm->subject->renderErrors()?>
                        </div>
                    </div>

					<div class="row">
                        <div class="medium-12 columns">
                            <?php echo $this->contactForm->message->renderViewHelper();?>
							<?php echo $this->contactForm->message->renderErrors()?>
                        </div>
                    </div>
					
					
					<div class="row">
                        <div class="small-12 medium-8 medium-offset-2 end columns captcha">
							<?php echo $this->contactForm->captcha->render()?>
					    </div>
                    </div>
					
					<div class="row">
                        <div class="small-12 columns text-center">
                            <?php echo $this->contactForm->send->renderViewHelper();?>
                        </div>
                    </div>
            </form>

        <?php endif; ?>

<?php endif; ?>

