	<div class="row">
	<div class="large-10 columns margin-box">
<?php if($this->correspondenceDataEnable) : ?>
  

		<h3><?php echo $this->correspondenceDataSectionTitle; ?></h3>
			
		<?php if($this->correspondenceDataAddressEnable) : ?>
		
			<p class="padding">
			   <?php echo $this->businessCardTitle; ?>
			</p>
			
            <p class="padding">
                <span class="name1">Adres:</span> <?php echo $this->correspondenceDataAddressStreet; ?> <?php echo $this->correspondenceDataAddressLocalNumber; ?>
            </p>
                         
             <p class="padding">
               <?php echo $this->correspondenceDataAddressZipCode; ?> <?php echo $this->correspondenceDataAddressCity; ?>
            </p>
                         
        <?php endif; ?>

        <?php if($this->correspondenceDataPhoneEnable) : ?>
                         
             <p class="padding"><span class="name3">Telefon:</span> <?php echo $this->correspondenceDataPhoneValue; ?></p>
                         
        <?php endif; ?>
          
  
		
		

<?php endif; ?>



</div>
</div>