<?php if($this->detailsDataEnable) : ?>
	<div class="row">
	<div class="large-12 columns">

		<h2><?php echo $this->detailsDataSectionTitle; ?></h2> 
		</div>
	</div>

	
	<div class="row">
		<div class="large-5 medium-3 small-12 columns">

	 <?php if($this->detailsDataAddressEnable) : ?>
        <h3>Adres:</h3> 
		<p>
		<?php echo $this->detailsDataAddressStreet; ?>
		<?php echo $this->detailsDataAddressLocalNumber; ?><br />
		<?php echo $this->detailsDataAddressZipCode; ?>
		<?php echo $this->detailsDataAddressCity; ?>
		</p>
    <?php endif; ?> <!-- adres -->


</div>


</div>
<div class="row margin-box">
	<div class="large-3 medium-3 small-12 columns">
    <?php if($this->detailsDataLinkEnable) : ?>
        <h3>Adres WWW:</h3><p> <a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?></a></p>
    <?php endif; ?>
	</div>
</div>


<div class="row margin-box">
		<div class="large-3 medium-3 small-12 columns">

	    <?php if($this->detailsDataNipEnable) : ?>
        <h3>NIP:</h3><p><?php echo $this->detailsDataNipValue; ?></p>
    <?php endif; ?>

	
	</div>
	
	

		
	
	
	
<div class="row margin-box2">
		<div class="large-12 medium-12 small-12 columns">
		<div class="bg_samolot">
			<img class="samolot" src="<?=$this->tplMediaUrl('992', '/images/samolot.png'); ?>">	
		</div>
		<div class="mail_box">
			<?php if($this->detailsDataEmailEnable) : ?>
				<a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a>
			<?php endif; ?>
			
			<p>	
    <?php if($this->detailsDataPhoneEnable) : ?>
       <?php echo $this->detailsDataPhoneValue; ?>
    <?php endif; ?></p>
		</div>
</div>
</div>
	

<div class="large-12 medium-12 small-12 columns">
		<div id="social_ico">
<?php if($this->socialMediaEnable) : ?>	
			<?php if($this->socialMediaFacebookEnable) : ?>
				<a target="_blank" href="<?php echo $this->socialMediaFacebookUrl; ?>"><div class="social social1"></div></a>
			<?php endif; ?>
	
		

			<?php if($this->socialMediaInstagramEnable) : ?>
				<a target="_blank" href="<?php echo $this->socialMediaInstagramUrl; ?>"><div class="social social4"></div></a>
			<?php endif; ?>
	

			<?php if($this->socialMediaTwitterEnable) : ?>
				<a target="_blank" href="<?php echo $this->socialMediaTwitterUrl; ?>"><div class="social social2"></div></a>
			<?php endif; ?>

		

			<?php if($this->socialMediaLinkedInEnable) : ?>
				<a target="_blank" href="<?php echo $this->socialMediaLinkedInUrl; ?>"><div class="social social6"></div></a>
			<?php endif; ?>

		

			<?php if($this->socialMediaGooglePlusEnable) : ?>
				<a target="_blank" href="<?php echo $this->socialMediaGooglePlusUrl; ?>"><div class="social social3"></div></a>
			<?php endif; ?>

		

			<?php if($this->socialMediaYouTubeEnable) : ?>
				<a target="_blank" href="<?php echo $this->socialMediaYouTubeUrl; ?>"><div class="social social5"></div></a>
			<?php endif; ?>
<?php endif; ?>
	
	</div>

	
	
	</div>

	

	</div>




	
	


<?php endif; ?>				
