<?php if($this->detailsDataEnable) : ?>

		
		<?php if($this->detailsDataAddressEnable) : ?>
			<div class="large-6 medium-6 small-12 columns">
				<h2>Adres:</h2> 
				<p><?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?></p>
				<p><?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?></p>
			</div>	
		<?php endif; ?>
		
		<?php if($this->detailsDataEmailEnable) : ?>
			<div class="large-6 medium-6 small-12 columns">
				<h2>E-mail</h2>
				<p><a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a></p>
			</div>
		<?php endif; ?>
		
<div class="padding_box">&nbsp;</div>
		
		<?php if($this->detailsDataPhoneEnable) : ?>
			<div class="large-6 medium-6 small-12 columns">
				<h2>Telefon</h2>
				<p><?php echo $this->detailsDataPhoneValue; ?></p>
			</div>
		<?php endif; ?>
		
		<?php if($this->detailsDataNipEnable) : ?>
			<div class="large-6 medium-6 small-12 columns">
				<h2>NIP:</h2>
				<p><?php echo $this->detailsDataNipValue; ?></p>
			</div>
		<?php endif; ?>
		
<div class="padding_box">&nbsp;</div>
		
		<?php if($this->detailsDataLinkEnable) : ?>
			<div class="large-6 medium-12 small-12 columns">
				<h2>Strona WWW</h2>
				<p><a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?></a></p>
			</div>
		<?php endif; ?>
		

<?php endif; ?>				
