<?php if($this->basicInfoEnable) : ?>
	
	<p class="headerSlider slide1"><span><?php echo $this->basicInfoSectionTitle; ?></span><span class="arrowSpan"></span></p>
	
	<div class="contentSlider">
		<p class="header_column slid1"><?php echo $this->basicInfoSectionTitle; ?></p>
		<p class="about_factory"><?php echo $this->basicInfoDescription; ?></p>
	</div><!-- contentSlider -->
	
<?php endif; ?>

						
						
						
