<?php if($this->formEnable) : ?>

	<p class="headerSlider slide5"><span><?php echo $this->formSectionTitle; ?></span><span class="arrowSpan"></span></p>
			<div class="contentSlider">
			<p class="header_column" style="padding-left: 15px; padding-top: 12px;">

        <?php if ($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>

            <h2>Dziękujemy za przesłanie wiadomości!</h2>

            <script>
			
				$(document).ready(function() {
					$('.slider .contentSlider').hide(); 
		
					$('.slider .slide5').next('.contentSlider').show(); 
					$('.slider .headerSlider.slide5').addClass('active'); 
				});
				
            </script>
        <?php endif ?>

        <?php if ($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>

            <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
                  <script>
				  
					$(document).ready(function() {
                        $('.slider .contentSlider').hide(); 
	
						$('.slider .slide5').next('.contentSlider').show(); 
						$('.slider .headerSlider.slide5').addClass('active'); 
					});
					
                    </script>
            <?php endif; ?>

			
			
		<?php echo $this->formSectionTitle; ?></p>
			
				<form action="<?=$this->contactForm->getAction()?>" method="<?=$this->contactForm->getMethod();?>">

                <div class="large-6 medium-6 columns">
                    <?php echo $this->contactForm->email->renderViewHelper();?>
                    <?php echo $this->contactForm->email->renderErrors()?>
                </div><!-- large-6 medium-6 columns -->

                <div class="large-6 medium-6 columns">
                    <?php echo $this->contactForm->phone->renderViewHelper();?>
                    <?php echo $this->contactForm->phone->renderErrors()?>
                </div><!-- large-6 medium-6 columns -->

                <div class="large-12 columns">
                    <?php echo $this->contactForm->subject->renderViewHelper();?>
                    <?php echo $this->contactForm->subject->renderErrors()?>
                </div><!-- large-12 columns -->

                <div class="large-12 columns">
                    <?php echo $this->contactForm->message->renderViewHelper();?>
                    <?php echo $this->contactForm->message->renderErrors()?>
                </div><!-- large-12 columns -->

                <div class="large-12 columns">
                    <div class="pull-left">
                        <div id="captchaContainer" class="left">
                            <?php echo $this->contactForm->captcha->render()?>
                        </div>
                    </div>

                    <div class="right">
                        <?php echo $this->contactForm->send->renderViewHelper();?>
                    </div>
                </div>

            </form>
			
			
			</div><!-- contentSlider -->

        <?php endif; ?>

<?php endif; ?>


			

					
					
					




