<?php if($this->mapEnable) : ?>

    <p class="headerSlider slide4 mapInvoker"><span><?php echo $this->mapSectionTitle; ?></span><span class="arrowSpan"></span></p>

    <div class="contentSlider paddingNone">
        <div class="maps">

            <?php include "./common/templates/mapframestrategyonclick.phtml"; ?>

        </div> <!-- maps -->
    </div><!-- contentSlider -->

<?php endif; ?>

