<?php if($this->correspondenceDataEnable) : ?>

 <div class="part corespond"> 
		<p class="titleAdres"><?php echo $this->correspondenceDataSectionTitle; ?></p>
		<?php if($this->correspondenceDataAddressEnable) : ?>
		
			<p class="adresKorespondencja">
				<span><?php echo $this->businessCardTitle; ?></span>
				<span><?php echo $this->correspondenceDataAddressStreet; ?> <?php echo $this->correspondenceDataAddressLocalNumber; ?></span>
				<span><?php echo $this->correspondenceDataAddressZipCode; ?> <?php echo $this->correspondenceDataAddressCity; ?></span>
			</p>
                         
        <?php endif; ?>

        <?php if($this->correspondenceDataPhoneEnable) : ?>
                         
             <p class="padding"><span class="name3">Telefon:</span> <?php echo $this->correspondenceDataPhoneValue; ?></p>
                         
        <?php endif; ?>
          
		</div><!-- part -->		

<?php endif; ?>

