<?php if($this->detailsDataEnable) : ?>

	<div class="box"><p class="titleSection"><?php echo $this->detailsDataSectionTitle; ?></p><!-- titleSection --></div><!-- box -->
	
	 <div class="part"> 
		
		 <?php if($this->detailsDataAddressEnable) : ?>
			<p class="titleAdres">Adres:</p>
			<p class="ulica"><?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?></p>
			<p class="kod"><?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?></p>
<br /><br />
		<?php endif; ?>
		
		

		<?php if($this->detailsDataPhoneEnable) : ?>
			<p class="telefon"><span>Telefon:</span> <?php echo $this->detailsDataPhoneValue; ?></p>
		<?php endif; ?>

		<?php if($this->detailsDataEmailEnable) : ?>
			<p class="email"><span>E-mail:</span> <a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a></p>
		<?php endif; ?>

		<?php if($this->detailsDataNipEnable) : ?>
			<p class="nip"><span>NIP:</span> <?php echo $this->detailsDataNipValue; ?></p>
		<?php endif; ?>

		<?php if($this->detailsDataLinkEnable) : ?>
			<p class="Facebook"><span>Strona WWW: </span> <a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?></a></p>
		<?php endif; ?>
	</div><!-- part -->
	
	
<?php endif; ?>				
