<?php if($this->correspondenceDataEnable) : ?>
   
      <!--  <?php echo $this->correspondenceDataSectionTitle; ?> -->


    <!-- warstwa adres do korespondencji -->
   
        <p class="header_column"><?php echo $this->correspondenceDataSectionTitle; ?></p>

            <p class="Adress">
                <?php echo $this->businessCardTitle; ?>
            </p>
                        
            <?php if($this->correspondenceDataAddressEnable) : ?>
                         
            <p class="Adress">
               <span class="name3">Adres: </span> <span class="widthLeft"> <?php echo $this->correspondenceDataAddressStreet; ?> <?php echo $this->correspondenceDataAddressLocalNumber; ?><span class="newLine"><?php echo $this->correspondenceDataAddressZipCode; ?> <?php echo $this->correspondenceDataAddressCity; ?></span></span></p>
            </p>
                         
            <?php endif; ?>

            <?php if($this->correspondenceDataPhoneEnable) : ?>
                         
                  <p class="Phone"><span class="name3">Telefon:</span> <?php echo $this->correspondenceDataPhoneValue; ?></p>
                         
            <?php endif; ?>

<?php endif; ?>

