<?php if($this->formEnable) : ?>


    <div id="formularz-do-korespondencji-szczegoly" class="row mfp-hide paddingLeftNoneFormularz">

        <?php if ($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>

            <h2>Dziękujemy za przesłanie wiadomości!</h2>

				<script>
                    $(document).ready(function() {
                        $('.link-to-page[href="#contact-us"]').click();
                    });
                </script>
				
        <?php endif ?>

        <?php if ($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>

            <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
			
                 <script>
                    $(document).ready(function() {
                        $('.link-to-page[href="#contact-us"]').click();
                    });
                </script>
				
            <?php endif; ?>
		<div class="large-12 columns paddingLeft_Cancel mobile_no_padding">
			<p class="header_column"><?php echo $this->formSectionTitle; ?></p>

            <form action="<?=$this->contactForm->getAction()?>" method="<?=$this->contactForm->getMethod();?>">

                <div class="large-6 medium-6 columns paddingLeftNone">
                    <?php echo $this->contactForm->email->renderViewHelper();?>
                    <?php echo $this->contactForm->email->renderErrors()?>
                </div><!-- large-6 medium-6 columns -->

                <div class="large-6 medium-6 columns paddingLeftNoneSecond">
                    <?php echo $this->contactForm->phone->renderViewHelper();?>
                    <?php echo $this->contactForm->phone->renderErrors()?>
                </div><!-- large-6 medium-6 columns -->

                <div class="large-12 columns paddingLeftNone">
                    <?php echo $this->contactForm->subject->renderViewHelper();?>
                    <?php echo $this->contactForm->subject->renderErrors()?>
                </div><!-- large-12 columns -->

                <div class="large-12 columns paddingLeftNone">
                    <?php echo $this->contactForm->message->renderViewHelper();?>
                    <?php echo $this->contactForm->message->renderErrors()?>
                </div><!-- large-12 columns -->

				<div class="pnlSend">
					<div class="large-12 medium-12 columns paddingLeftNone">
						<div class="pull-left">
							<div id="captchaContainer" class="left">
								<?php echo $this->contactForm->captcha->render()?>
							</div>
						</div>

						<div class="right">
							<?php echo $this->contactForm->send->renderViewHelper();?>
						</div>
					</div><!-- large-12 medium-12 columns -->
				</div> <!-- pnlSend -->

            </form>
		</div><!-- large-12 columns -->

        <?php endif; ?>


    </div>


<?php endif; ?>


  


