<?php if($this->basicInfoEnable) : ?>

	<div class="row">
		<div class="large-12 columns">
			<div class="panel">
				<h1><?php echo $this->businessCardTitle; ?></h1>
				<p class="titleSection"><?php echo $this->basicInfoSectionTitle; ?></p>
				<p class="about_factory contentHeight"><?php echo $this->basicInfoDescription; ?></p>
   			</div><!-- panel --> 
		</div><!-- large-12 columns bg -->
	</div><!-- row -->
   
<?php endif; ?>







