<?php if($this->detailsDataEnable) : ?>

				<div class="large-12 columns">
					<h2><?php echo $this->businessCardTitle; ?></h2>
					<p class="titleSection"><?php echo $this->detailsDataSectionTitle; ?></p>
				</div><!-- large-12 column -->	
				
				
				
				<!-- Telefon -->
				<div class="large-6 medium-6 columns" style="color: white;">
				
					<?php if($this->detailsDataPhoneEnable) : ?>
						<p class="Phone"><span class="spanTitle">Telefon:</span><?php echo $this->detailsDataPhoneValue; ?></p>
					<?php endif; ?>
				</div>

				<!-- Adres E-mail -->
				<div class="large-6 medium-6 columns" style="color: white;">	
					<?php if($this->detailsDataEmailEnable) : ?>
						<p class="Email">
							<span class="spanTitle">E-mail:</span>
								<a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a>
						</p>
					<?php endif; ?>
				</div>	
					
					
					
				<!-- Adres -->
				<div class="large-6 medium-6 columns" style="color: white;">		
					<?php if($this->detailsDataAddressEnable) : ?>
						<p class="Adress"><span class="spanTitle">Adres:</span><?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?><span> <?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?></span></p>
					<?php endif; ?>
				</div>	
				
				
				
				<!-- NIP -->
				<div class="large-6 medium-6 columns" style="color: white;">
					<?php if($this->detailsDataNipEnable) : ?>
						<p class="Nip"><span class="spanTitle">NIP:</span>  <?php echo $this->detailsDataNipValue; ?></p>
					<?php endif; ?>
				</div>
					
					
					
				<!-- Adres WWW -->
				<div class="large-6 medium-6 columns" style="color: white;">
					<?php if($this->detailsDataLinkEnable) : ?>
						<p class="Nip"><span class="spanTitle">Adres WWW:</span> <a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?> </a></p>
					<?php endif; ?>
				</div><!-- large-6 medium-6 columns -->	
				
					
				<div class="large-6 medium-6 columns" style="color: white;">	
								
								<?php if($this->socialMediaEnable) : ?>
								<p class="social"><span class="spanTitle">Obserwuj nas na:</span>
								<ul class="SocialList">
									
										<?php if($this->socialMediaFacebookEnable) : ?>
										<li class="facebook">
											<a href="<?php echo $this->socialMediaFacebookUrl; ?>" class="facebook" target="_blank">facebook</a>
										</li>
										<?php endif; ?>
									
									
									
										<?php if($this->socialMediaInstagramEnable) : ?>
										<li class="instagram">
											<a href="<?php echo $this->socialMediaInstagramUrl; ?>" class="instagram" target="_blank">instagram</a>
											</li>
										<?php endif; ?>
									
									
									
										<?php if($this->socialMediaTwitterEnable) : ?>
										<li class="twitter">
											<a href="<?php echo $this->socialMediaTwitterUrl; ?>" class="twitter" target="_blank">twitter</a>
											</li>
										<?php endif; ?>
									
									
									
										<?php if($this->socialMediaLinkedInEnable) : ?>
										<li class="linkedIn">
											<a href="<?php echo $this->socialMediaLinkedInUrl; ?>" class="linkedIn" target="_blank">linkedin</a>
											</li>
										<?php endif; ?>
									
									
									
										<?php if($this->socialMediaGooglePlusEnable) : ?>
										<li class="googlePlus">
											<a href="<?php echo $this->socialMediaGooglePlusUrl; ?>" class="google_plus" target="_blank">google plus</a>
											</li>
										<?php endif; ?>
									
									
									
										<?php if($this->socialMediaYouTubeEnable) : ?>
										<li class="youTube">
											<a href="<?php echo $this->socialMediaYouTubeUrl; ?>" class="youTube" target="_blank">youtube</a>
											</li>
										<?php endif; ?>
									
								
								</ul></p>
								<?php endif; ?>
				</div><!-- large-6 medium-6 columns -->	
						
					
					
				

				
					
							
						
			

<?php endif; ?>








  
	
	


   

   

   

  
	
	


