<?php if($this->formEnable) : ?>

	

		<?php if ($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>

            <h3 style="padding: 350px 0 300px !important;">Dziękujemy za przesłanie wiadomości!</h3>

				<script>
                    $(document).ready(function() {
						var offsetScroll = -50; //Offset of 20px
							$("html, body").animate({
								scrollTop: $('#formularz').offset().top + offsetScroll
						}, 1);
                    });
                </script>
				
				
        <?php endif ?>

	
	
        <?php if ($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>

            <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
					<script>
                        $(document).ready(function() {
							var offsetScroll = -50; //Offset of 20px
							  $("html, body").animate({
								scrollTop: $('#formularz').offset().top + offsetScroll
							}, 1);
                        });
                    </script>
            <?php endif; ?>

			<div class="row">
				<div class="large-12 columns">
				<h2><?php echo $this->businessCardTitle; ?></h2>
					<div class="panel">
						<p class="titleSection"><?php echo $this->formSectionTitle; ?></p>
			
			

							<form action="<?=$this->contactForm->getAction()?>" method="<?=$this->contactForm->getMethod();?>">

							
								<div class="large-6 medium-6 columns">
									<div class="textInput"><?php echo $this->contactForm->email->renderViewHelper();?></div>
									<?php echo $this->contactForm->email->renderErrors()?>
								</div><!-- large-6 medium-6 columns -->

								<div class="large-6 medium-6 columns">
									<div class="textInput"><?php echo $this->contactForm->phone->renderViewHelper();?></div>
									<?php echo $this->contactForm->phone->renderErrors()?>
								</div><!-- large-6 medium-6 columns -->

								<div class="large-12 columns">
									<div class="textInput news"><?php echo $this->contactForm->subject->renderViewHelper();?></div>
									<?php echo $this->contactForm->subject->renderErrors()?>
								</div><!-- large-12 columns -->

								<div class="large-12 columns">
									<div class="require textarea"><?php echo $this->contactForm->message->renderViewHelper();?></div>
									<?php echo $this->contactForm->message->renderErrors()?>
								</div><!-- large-12 columns -->
								
								
								
								<div class="pnlSend">

									<div class="large-12 medium-12 columns">
										<div id="captchaContainer" class="left">
											<?php echo $this->contactForm->captcha->render()?>
										</div>
										
										<div class="left space">
											<?php echo $this->contactForm->send->renderViewHelper();?>
										</div>
									</div><!-- large-12 medium-12 columns -->
									
								</div> <!-- pnlSend -->

							</form>
							
					</div><!-- panel -->
				</div><!-- large-12 columns -->
			</div><!-- row -->

        <?php endif; ?>




<?php endif; ?>



