<?php if($this->offerEnable) : ?>
	<div class="row">
		<div class="large-12 columns">
			<div class="panel">
				<h2><?php echo $this->businessCardTitle; ?></h2>
				<p class="titleSection"><?php echo $this->offerSectionTitle; ?></p>
				<div class="contentHeight">
					<?php echo htmlspecialchars_decode($this->offerContent); ?>
				</div><!-- contentHeight -->
			</div><!-- panel -->
		</div> <!-- large-12 columns -->
	</div><!-- row -->
<?php endif; ?>		
