<?php if($this->detailsDataEnable) : ?>

		<h2><?php echo $this->detailsDataSectionTitle; ?></h2>

		<?php if($this->detailsDataAddressEnable) : ?>
			<p class="info-block info-block-place">
				<span class="info-block-icon"></span>
				<strong>Adres:</strong>
				<br />
				<?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?>
				<br />
				<?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?>
			</p>
		<?php endif; ?>

		
		
		<p class="info-block info-block-phone">
		
			<?php if($this->detailsDataPhoneEnable) : ?>
					<span class="info-block-icon"></span>
					<strong>Tel.:</strong>  <?php echo $this->detailsDataPhoneValue; ?>
			<br /><?php endif; ?>	
			
			
			
			<?php if($this->detailsDataEmailEnable) : ?>
				<strong>E-mail:</strong> <a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a>
			<br /><?php endif; ?>	
				
			
			
			<?php if($this->detailsDataNipEnable) : ?>
				<strong>NIP:</strong> <?php echo $this->detailsDataNipValue; ?>
			<br /><?php endif; ?>
			
			
			
			<?php if($this->detailsDataLinkEnable) : ?>
				<strong>Adres WWW: </strong> <a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?></a>
			<?php endif; ?>
		</p>
		
		<?php if($this->socialMediaEnable) : ?>
		
	<ul class="inline-list info-block info-block-social">
        <span class="info-block-icon"></span>
		<li>
			<?php if($this->socialMediaFacebookEnable) : ?>
				<a href="<?php echo $this->socialMediaFacebookUrl; ?>" class="fb" target="_blank"><span>facebook</span></a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaInstagramEnable) : ?>
				<a href="<?php echo $this->socialMediaInstagramUrl; ?>" class="ig" target="_blank"><span>instagram</span></a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaTwitterEnable) : ?>
				<a href="<?php echo $this->socialMediaTwitterUrl; ?>" class="tw" target="_blank"><span>twitter</span></a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaLinkedInEnable) : ?>
				<a href="<?php echo $this->socialMediaLinkedInUrl; ?>" class="li" target="_blank"><span>linkedin</span></a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaGooglePlusEnable) : ?>
				<a href="<?php echo $this->socialMediaGooglePlusUrl; ?>" class="gp" target="_blank"><span>google plus</span></a>
			<?php endif; ?>
		</li>
					
		<li>
			<?php if($this->socialMediaYouTubeEnable) : ?>
				<a href="<?php echo $this->socialMediaYouTubeUrl; ?>" class="yt" target="_blank"><span>youtube</span></a>
			<?php endif; ?>
		</li>					
                                       
    </ul>

	<?php endif; ?>
		

<?php endif; ?>
	
