<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><?php echo $this->businessCardTitle; ?></title>
    <style>
        * {margin: 0; padding: 0; border: 0 none;}
        html, body {width: 100%; height: 100%;}
        #googleMap {width: 100%; height: 100%;}
    </style>
</head>
<body>

<script src="<?=$this->baseUrl('common/js/jquery-2.1.3.js'); ?>" type="text/javascript"></script>
<script src="//maps.googleapis.com/maps/api/js?region=PL&key=<?php echo $this->mapApiKeyEnable ? $this->mapApiKey : $this->globalGoogleMapsApiKey() ?>"></script>
