<?php include "./common/templates/mapheader.phtml"; ?>

    <script type="text/javascript">

        var mapa1;
        var lokalizacja;
        var MY_MAPTYPE_ID = 'custom_style';
        var geocoder = new google.maps.Geocoder();

        function initialize() {
            <?php if(is_numeric($this->mapLat) && is_numeric($this->mapLng)) : ?>
            var mapLat = <?php echo $this->mapLat; ?>;
            var mapLng = <?php echo $this->mapLng; ?>;
            lokalizacja = new google.maps.LatLng(mapLat, mapLng);
            enableMap();
            <?php else : ?>
            var address = "<?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?> <?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?>";
            geocoder.geocode({'address': address}, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    lokalizacja = new google.maps.LatLng(results[0].geometry.location.lat(), results[0].geometry.location.lng());
                    enableMap();
                } else {
                    $("#googleMap").html('<p class="about_factory">Nie można wyświetlic mapy.<br />Wskazana lokalizacja jest niepoprawna.</p>');
                }
            });
            <?php endif; ?>
        }

        function enableMap() {
            var isMobile = true;
            if (window.matchMedia) {
                isMobile = !window.matchMedia('(max-device-width: 600px)').matches;
            }
            var mapOptions = {                              // DEFINICJA PARAMETRÓW MAPY
                center: lokalizacja,                    // ustalenie środka mapy
                zoom:15,                                    // ustalenie stopnia przybliżenia

                panControl: false,                          // kontrolka kierunku mapy
                zoomControl: true,                          // kontrolka przyblizenia
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.SMALL
                },
                mapTypeControl: true,                       // kontrolka typu mapy
                scaleControl: true,                         // kontrolka widocznosci skali
                streetViewControl: false,                   // kontrolka streetView
                overviewMapControl: false,                  // kontrolka małej mapy w rogu
                scrollwheel: false,                         // wyłączenie scrolowania mapy
                draggable: isMobile,
                mapTypeId: MY_MAPTYPE_ID,
                mapTypeControlOptions: {
                    mapTypeIds: [google.maps.MapTypeId.ROADMAP, MY_MAPTYPE_ID]
                }
                //mapTypeId:google.maps.MapTypeId.ROADMAP   // typ mapy do wyświetlenia
            };

            mapa1 = new google.maps.Map(document.getElementById("googleMap"),mapOptions);

            var styleOpts = [
                {
                    "featureType": "all",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#544c60"
                        }
                    ]
                },
                {
                    "featureType": "all",
                    "elementType": "labels.text.fill",
                    "stylers": [
                        {
                            "gamma": 0.01
                        },
                        {
                            "lightness": 20
                        }
                    ]
                },
                {
                    "featureType": "all",
                    "elementType": "labels.text.stroke",
                    "stylers": [
                        {
                            "saturation": -31
                        },
                        {
                            "lightness": -33
                        },
                        {
                            "weight": 2
                        },
                        {
                            "gamma": 0.8
                        }
                    ]
                },
                {
                    "featureType": "all",
                    "elementType": "labels.icon",
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "administrative",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#ff0000"
                        }
                    ]
                },
                {
                    "featureType": "administrative",
                    "elementType": "labels.text",
                    "stylers": [
                        {
                            "color": "#ad8989"
                        }
                    ]
                },
                {
                    "featureType": "administrative.country",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#ff0000"
                        }
                    ]
                },
                {
                    "featureType": "administrative.province",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#ff0000"
                        }
                    ]
                },
                {
                    "featureType": "administrative.province",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#634568"
                        }
                    ]
                },
                {
                    "featureType": "administrative.province",
                    "elementType": "labels",
                    "stylers": [
                        {
                            "color": "#654f76"
                        }
                    ]
                },
                {
                    "featureType": "administrative.locality",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#ab82be"
                        },
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "administrative.neighborhood",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#695578"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#453d52"
                        },
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "lightness": 30
                        },
                        {
                            "saturation": 30
                        },
                        {
                            "color": "#5d4e74"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "geometry.fill",
                    "stylers": [
                        {
                            "color": "#4f4363"
                        },
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "geometry.stroke",
                    "stylers": [
                        {
                            "color": "#2a1d3f"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "labels.text.fill",
                    "stylers": [
                        {
                            "color": "#2a1d3f"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "labels.text.stroke",
                    "stylers": [
                        {
                            "color": "#2a1d3f"
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "labels.icon",
                    "stylers": [
                        {
                            "color": "#2a1d3f"
                        }
                    ]
                },
                {
                    "featureType": "landscape.man_made",
                    "elementType": "geometry.fill",
                    "stylers": [
                        {
                            "color": "#5c516c"
                        },
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "landscape.man_made",
                    "elementType": "geometry.stroke",
                    "stylers": [
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "landscape.natural.landcover",
                    "elementType": "all",
                    "stylers": [
                        {
                            "saturation": "0"
                        },
                        {
                            "color": "#ec0000"
                        }
                    ]
                },
                {
                    "featureType": "poi",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "saturation": 20
                        }
                    ]
                },
                {
                    "featureType": "poi.park",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "lightness": 20
                        },
                        {
                            "saturation": -20
                        }
                    ]
                },
                {
                    "featureType": "road",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#544669"
                        },
                        {
                            "visibility": "simplified"
                        }
                    ]
                },
                {
                    "featureType": "road",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "lightness": 10
                        },
                        {
                            "saturation": -30
                        }
                    ]
                },
                {
                    "featureType": "road",
                    "elementType": "geometry.stroke",
                    "stylers": [
                        {
                            "saturation": 25
                        },
                        {
                            "lightness": 25
                        }
                    ]
                },
                {
                    "featureType": "transit",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#453c52"
                        },
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "transit.station",
                    "elementType": "all",
                    "stylers": [
                        {
                            "color": "#3d3844"
                        },
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "water",
                    "elementType": "all",
                    "stylers": [
                        {
                            "lightness": -20
                        }
                    ]
                }
            ]

            var styledMapOptions = {
                name: 'Skala szarości'
            };
            var customMapType = new google.maps.StyledMapType(styleOpts, styledMapOptions);
            mapa1.mapTypes.set(MY_MAPTYPE_ID, customMapType);


            // DODATKOWE ELEMENTY NA MAPIE
            var iconBase = "<?=$this->tplMediaUrl('888', '/images/marker.png'); ?>";
            var marker = new google.maps.Marker({           // DODAWANIE MARKERA
                position: lokalizacja,
                map: mapa1,
                title: escape("<?php echo $this->mapSectionTitle; ?>"),
                draggable:false, // true                              // możliwość przenoszenia markera
                icon: iconBase
            });

            var infowindow = new google.maps.InfoWindow({   // DODANIE CHMURKI PRZY MARKERZE
                content: "<?php echo $this->businessCardTitle; ?>",
                escape: true
            });

            // EVENT LISTENERS
            google.maps.event.addListener(marker, 'click', function() { // DODANIE KLIKNIECIA NA MARKER
                infowindow.open(mapa1,marker);
            });

        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>

<?php include "./common/templates/mapfooter.phtml"; ?>