	<div id="mobile-navigation" style="height: 60px;">
		<div class="burger"></div>
		<div class="menu-list">
			<ul class="menuHeader">
				<li><a target="_self" class="linkToSection" href="#oNas"><?php echo $this->basicInfoSectionTitle; ?></a></li>
				<li><a target="_self" class="linkToSection" href="#daneFirmowe"><?php echo $this->detailsDataSectionTitle; ?></a></li>
				<li><a target="_self" class="linkToSection" href="#oferta"><?php echo $this->offerSectionTitle; ?></a></li>
				<li><a target="_self" class="linkToSection map" href="#lokalizacja"><?php echo $this->mapSectionTitle; ?></a></li>
			</ul>
		</div>
	</div><!-- mobile-navigation -->


	<ul id="nav">
		<li class="current"><a target="_self" href="#oNas" class="hint--left" data-hint="<?php echo $this->basicInfoSectionTitle; ?>"><?php echo $this->basicInfoSectionTitle; ?></a></li>
		<li><a target="_self" href="#daneFirmowe" class="hint--left" data-hint="<?php echo $this->detailsDataSectionTitle; ?>"><?php echo $this->detailsDataSectionTitle; ?></a></li>
		<li><a target="_self" href="#oferta" class="hint--left" data-hint="<?php echo $this->offerSectionTitle; ?>"><?php echo $this->offerSectionTitle; ?></a></li>
		<li><a target="_self" href="#lokalizacja" class="hint--left" data-hint="<?php echo $this->mapSectionTitle; ?>"><?php echo $this->mapSectionTitle; ?></a></li>
	</ul>

	<p style="position: fixed; margin: 20px; z-index: 1;"><button id="trigger-overlay" type="button"></button></p>

	<div id="container">
	
		<div class="section" id="oNas">
			<?php include 'partials/basicinfo.phtml'; ?>
			<a class="allLink" href="#daneFirmowe">dol</a>
		</div>
		
		
		
		<div class="section" id="daneFirmowe">
		
			<div class="row">
					
				<div class="contentHeight">	
					<div class="large-12 columns">	
						<div class="panel">
							<?php include 'partials/detailsdata.phtml'; ?>
						</div><!-- panel -->
<div class="large-12 columns">
<div class="panel">
<?php include 'partials/correspondencedata.phtml'; ?>
</div>
</div>
					</div><!-- large-12 column -->	
						
				
				</div><!-- contentHeight -->
			</div><!-- row -->
		
			<a class="allLink" href="#oferta">dol</a>
		</div>
		
		<div class="section" id="oferta">
			<?php include 'partials/offerdata.phtml'; ?>
			<a class="allLink" href="#lokalizacja">dol</a>
		</div>
		

		<div class="section" id="lokalizacja">
			<div class="large-12 columns fullSize map">
				<?php include 'partials/map.phtml'; ?>
			</div><!-- large-12 columns -->
		</div>

	</div><!-- container -->
	
	
	<div class="menuAll overlay overlay-contentscale">
        <button type="button" class="overlay-close">Zamknij</button>
        <nav>
            <ul>
                <li><a href="#oNas" data-index="1"><?php echo $this->basicInfoSectionTitle; ?></a></li>
                <li><a href="#daneFirmowe" data-index="2"><?php echo $this->detailsDataSectionTitle; ?></a></li>
				<li><a href="#oferta" data-index="3"><?php echo $this->offerSectionTitle; ?></a></li>
                <li><a href="#lokalizacja" data-index="4"><?php echo $this->mapSectionTitle; ?></a></li>
            </ul>
        </nav>
    </div>

	<script src="<?=$this->tplMediaUrl('888', '/js/demo7.js'); ?>" type="text/javascript"></script>
	

