<div class="bgTop">
	<div class="row">
		<div class="large-12 columns bg">
			<div class="panel">
				<?php include 'partials/mainheader.phtml'; ?>
				<hr class="redLine_default">
				<?php include 'partials/basicinfo.phtml'; ?>
			</div><!-- panel -->
		</div><!-- large-12 columns bg -->
	</div><!-- row -->
</div><!-- bgTop -->


    <div class="row">
		<div class="large-12 columns">
			<div class="panel">
				<div class="large-6 medium-6 columns center korespond">
					<?php include 'partials/detailsdata.phtml'; ?>
				</div><!-- large-6 medium-6 columns -->
				
				<div class="large-6 medium-6 columns center fontLato korespond">
					<?php include 'partials/correspondencedata.phtml'; ?>
				</div><!-- large-6 medium-6 columns -->	
				
			</div><!-- panel -->
		</div> <!-- large-12 columns -->
    </div><!-- row -->
	
	
	<div class="row">
		<div class="large-12 columns">
			<div class="panel">
				<?php include 'partials/offerdata.phtml'; ?>
			</div><!-- panel -->
		</div> <!-- large-12 columns -->
    </div><!-- row -->
	
