<?php if($this->formEnable) : ?>
<p class="links2">
    <a href="#formularz-do-korespondencji-szczegoly" <?php if ($this->showSuccessConfirmation) echo 'data-show-success="true"'; ?> title="" class="block4_Form fancybox"><?php echo $this->formSectionTitle; ?></a>
</p>

<div style="display: none;">
    <div id="formularz-do-korespondencji-szczegoly" class="row mfp-hide pop">
        <div class="large-12 columns">
        <div class="panel">
        <div class="row">

        <?php if ($this->showSuccessConfirmation) : /* SUCCESS MESSAGE */ ?>

            <h2>Dziękujemy za przesłanie wiadomości!</h2>

            <script>
                $(document).ready(function() {
                    $('.block4_Form.fancybox').click();
                });
            </script>
        <?php endif ?>

        <?php if ($this->showContactForm) : /* SUCCESS CONTACT FORM */ ?>

            <?php if($this->contactFormErrors) : /* SHOW FORM LAYER WHEN HAS ERRORS */ ?>
                  <script>
                        $(document).ready(function() {
                            $('.block4_Form.fancybox').click();
                        });
                    </script>
            <?php endif; ?>

            <h2><?php echo $this->formSectionTitle; ?></h2>

            <form action="<?=$this->contactForm->getAction()?>" method="<?=$this->contactForm->getMethod();?>">

                <div class="large-6 medium-6 columns">
                    <?php echo $this->contactForm->email->renderViewHelper();?>
                    <?php echo $this->contactForm->email->renderErrors()?>
                </div><!-- large-6 medium-6 columns -->

                <div class="large-6 medium-6 columns">
                    <?php echo $this->contactForm->phone->renderViewHelper();?>
                    <?php echo $this->contactForm->phone->renderErrors()?>
                </div><!-- large-6 medium-6 columns -->

                <div class="large-12 columns">
                    <?php echo $this->contactForm->subject->renderViewHelper();?>
                    <?php echo $this->contactForm->subject->renderErrors()?>
                </div><!-- large-12 columns -->

                <div class="large-12 columns">
                    <?php echo $this->contactForm->message->renderViewHelper();?>
                    <?php echo $this->contactForm->message->renderErrors()?>
                </div><!-- large-12 columns -->

                <div class="large-12 columns">
                    <div id="captchaContainer">
                        <?php echo $this->contactForm->captcha->render()?>
                    </div>

                    <div class="right">
                        <?php echo $this->contactForm->send->renderViewHelper();?>
                    </div>
                </div>

            </form>

        <?php endif; ?>

        </div>
        </div>
        </div>
    </div>
</div>

<?php endif; ?>
