<?php if($this->basicInfoEnable) : ?>

	<div class="content-column-2">	
		<div class="inside-div foto"></div>
	</div>

	<div class="content-column-2">
		<div class="inside-div description">
			<p class="head-2 header_column"><?php echo $this->basicInfoSectionTitle; ?></p>
			<p class="about_factory"><?php echo $this->basicInfoDescription; ?></p>
				
		</div><!-- inside-div description -->
	</div><!-- content-column-2 -->

<?php endif; ?>


