<?php if($this->detailsDataEnable) : ?>
	<div class="content-column-2">
		<div class="inside-div foto"></div>
	</div>
	
	
<div class="content-column-2">
	<div class="inside-div description">
	
	

		<p class="head-2 header_column"><?php echo $this->detailsDataSectionTitle; ?></p>

		<?php if($this->detailsDataAddressEnable) : ?>
			
			<p class="Center-name"><?php echo $this->businessCardTitle; ?></p>
			
			<p class="Adress"><span class="red-font">Adres:</span> <span class="widthLeft "><?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?><span class="newLine"><?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?><span></span></p>
		<?php endif; ?>

		<?php if($this->detailsDataPhoneEnable) : ?>
			<p class="Phone"><span class="red-font">Telefon:</span> <?php echo $this->detailsDataPhoneValue; ?></p>
		<?php endif; ?>

		<?php if($this->detailsDataEmailEnable) : ?>
			<p class="Email"><span class="red-font">E-mail:</span> <a href="mailto:<?php echo $this->detailsDataEmailValue; ?>"><?php echo $this->detailsDataEmailValue; ?></a></p>
		<?php endif; ?>

		<?php if($this->detailsDataNipEnable) : ?>
			<p class="Nip"><span class="red-font">NIP:</span> <?php echo $this->detailsDataNipValue; ?></p>
		<?php endif; ?>

		<?php if($this->detailsDataLinkEnable) : ?>
			<p class="Facebook"><span class="red-font">Adres WWW:</span> <a href="http://<?php echo $this->detailsDataLinkValue; ?>" target="_blank"><?php echo $this->detailsDataLinkValue; ?></a></p>
		<?php endif; ?>
	
	<?php if($this->socialMediaEnable) : ?>
	<ul class="menuSocial">
		<li>
			<?php if($this->socialMediaFacebookEnable) : ?>
				<a href="<?php echo $this->socialMediaFacebookUrl; ?>" class="facebook" target="_blank">facebook</a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaInstagramEnable) : ?>
				<a href="<?php echo $this->socialMediaInstagramUrl; ?>" class="instagram" target="_blank">instagram</a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaTwitterEnable) : ?>
				<a href="<?php echo $this->socialMediaTwitterUrl; ?>" class="twitter" target="_blank">twitter</a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaLinkedInEnable) : ?>
				<a href="<?php echo $this->socialMediaLinkedInUrl; ?>" class="linkedIn" target="_blank">linkedin</a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaGooglePlusEnable) : ?>
				<a href="<?php echo $this->socialMediaGooglePlusUrl; ?>" class="google_plus" target="_blank">google plus</a>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->socialMediaYouTubeEnable) : ?>
				<a href="<?php echo $this->socialMediaYouTubeUrl; ?>" class="youTube" target="_blank">youtube</a>
			<?php endif; ?>
		</li>
	
	</ul>	
<?php endif; ?>	
	


<?php endif; ?>





		
					
			