<?php if($this->offerEnable) : ?>

	<div class="content-column-2">	
		<div class="inside-div foto"></div>
	</div>

	<div class="content-column-2">
		<div class="inside-div description">
			<p class="head-2 header_column"><?php echo $this->offerSectionTitle; ?></p>
			<?php echo htmlspecialchars_decode($this->offerContent); ?>
				
		</div><!-- inside-div description -->
	</div><!-- content-column-2 -->
	
<?php endif; ?>		