	
	<div id="menu">
        <div id="menu-trigger"><span></span>Menu</div>
        <div id="menu-wrapper">
            <ul class="no-bullet" data-magellan-expedition data-options="offset_by_height: false;">
                <li class="head active" data-magellan-arrival="head"><a href="#head" target="_self"><span></span>Start</a></li>
                <li class="about" data-magellan-arrival="about"><a href="#about" target="_self"><span></span><?php echo $this->basicInfoSectionTitle; ?></a></li>
                <li class="info" data-magellan-arrival="info"><a href="#info" target="_self"><span></span><?php echo $this->detailsDataSectionTitle; ?></a></li>
                <li class="contact" data-magellan-arrival="contact"><a href="#contact" target="_self"><span></span><?php echo $this->formSectionTitle; ?></a></li>
            </ul>
        </div>
    </div>
	
	
	
	<div id="head" class="section section-line-bottom" data-magellan-destination="head" data-type="background" data-speed="10">
        <div class="row">
            <div class="small-12 large-8 large-offset-2 columns">
                <?php include 'partials/mainheader.phtml'; ?>
            </div>
        </div>
    </div>	


	<div id="about" class="section" data-magellan-destination="about">
        <div class="row">
            <div class="small-12 large-8 large-offset-2 columns">
                <?php include 'partials/basicinfo.phtml'; ?>
            </div>
        </div>
        <div class="row" data-magellan-expedition data-options="offset_by_height: false;">
            <div class="small-12 columns text-center chevron-down" data-magellan-arrival="info">
                <a href="#info" class="more"></a>
            </div>
        </div>
    </div>
	
	
	<div id="photo-1" class="section section-line-top section-line-bottom" data-type="background" data-speed="10">
    </div>

	<div id="info" class="section" data-magellan-destination="info">
        <div class="row">
            <div class="small-12 medium-6 large-4 large-offset-2 columns">
				<?php include 'partials/detailsdata.phtml'; ?>
            </div>
            <div class="small-12 medium-6 large-4 columns end">
				<?php include 'partials/correspondencedata.phtml'; ?>
            </div>
        </div>
		
		<div class="row" data-magellan-expedition data-options="offset_by_height: false;">
            <div class="small-12 columns text-center chevron-down" data-magellan-arrival="offer">
                <a href="#contact" class="more"></a>
            </div>
        </div>
    </div>
	
	
	<div id="photo-2" class="section section-line-top section-line-bottom" data-type="background" data-speed="10">
    </div>

		
	<div id="contact" class="section" data-magellan-destination="contact">
        <div class="row">
            <div class="small-12 large-8 large-offset-2 columns">
					<?php include 'partials/form.phtml'; ?>
            </div>
        </div>
    </div>
	
	
    <script src="<?=$this->tplMediaUrl('1112', '/js/jsmore/libs.min.js'); ?>"></script>
	<script src="<?=$this->tplMediaUrl('1112', '/js/foundation.min.js'); ?>"></script>
    <script src="<?=$this->tplMediaUrl('1112', '/js/custom.js'); ?>"></script>
	<script>
        $(document).foundation();
    </script>
	
	
