<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
    <meta charset="utf-8" />
    <base href="/">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">

    <title><?php echo $this->businessCardTitle; ?></title>
	
	<link rel="icon" href="<?=$this->tplMediaUrl('923', '/images/fav.ico'); ?>" type="image/x-icon" />
	<link rel="shortcut icon" href="<?=$this->tplMediaUrl('923', '/images/fav.ico'); ?>" type="image/x-icon" />
	   
	<link rel="stylesheet" href="<?=$this->tplMediaUrl('923', '/style/foundation.css'); ?>" />  
	<link rel="stylesheet" href="<?=$this->baseUrl('common/css/font-Lato-Light.css'); ?>" />
	<link rel="stylesheet" href="<?=$this->tplMediaUrl('923', '/style/style8.css'); ?>" />
	<link rel="stylesheet" href="<?=$this->tplMediaUrl('923', '/style/style.css'); ?>" />
	
	<script src="<?=$this->baseUrl('common/js/jquery-2.1.3.js'); ?>" type="text/javascript"></script>
	<script src="<?=$this->tplMediaUrl('923', '/js/modernizr.custom.js'); ?>" type="text/javascript"></script>
	<script src="<?=$this->tplMediaUrl('923', '/js/wiz.js'); ?>" type="text/javascript"></script>
	
	<script src="<?=$this->tplMediaUrl('923', '/js/library/classie.js'); ?>" type="text/javascript"></script>

</head>
<body>

<?php
    $templateVersion = 4;
    if ($this->mapEnable && $this->formEnable && !$this->offerEnable) {      
        $templateVersion = 1; // InfoPodstawowe + mapa + formularz
    } 
	elseif ($this->mapEnable && !$this->formEnable && !$this->offerEnable) { 
        $templateVersion = 2;  // InfoPodstawowe + mapa
    } 
	
	
	elseif (!$this->mapEnable && $this->formEnable && !$this->offerEnable) { 
        $templateVersion = 3; // InfoPodstawowe + formularz
    } 
	
	elseif (!$this->mapEnable && !$this->formEnable && $this->offerEnable) { 
        $templateVersion = 6; // InfoPodstawowe + oferta
    } 
	
	elseif (!$this->mapEnable && $this->formEnable && $this->offerEnable) { 
        $templateVersion = 7; // InfoPodstawowe + formularz + oferta
    } 
	
	elseif ($this->mapEnable && !$this->formEnable && $this->offerEnable) { 
        $templateVersion = 8; // InfoPodstawowe + mapa + oferta
    } 
	
	elseif ($this->mapEnable && $this->formEnable && $this->offerEnable) { 
        $templateVersion = 5; // InfoPodstawowe + mapa + formularz + oferta
	} else {                                          
        $templateVersion = 4;
    }
?>

<?php
	include 'version'.$templateVersion.'.phtml';

?> 


<script src="<?=$this->tplMediaUrl('923', '/js/waypoints.min.js'); ?>" type="text/javascript"></script>
		<script>
			var $head = $( '.nagl' );
			$( '.ha-waypoint' ).each( function(i) {
				var $el = $( this ),
					animClassDown = $el.data( 'animateDown' ),
					animClassUp = $el.data( 'animateUp' );

				$el.waypoint( function( direction ) {
					if( direction === 'down' && animClassDown ) {
						$head.attr('class', 'nagl ' + animClassDown);
					}
					else if( direction === 'up' && animClassUp ){
						$head.attr('class', 'nagl ' + animClassUp);
					}
				}, { offset: '1%' } );
			} );
			
			
			
		</script>


<script src="<?=$this->tplMediaUrl('923', '/js/demo1.js'); ?>" type="text/javascript"></script>
      <script>
			(function() {
				if (!String.prototype.trim) {
					(function() {
						// Make sure we trim BOM and NBSP
						var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
						String.prototype.trim = function() {
							return this.replace(rtrim, '');
						};
					})();
				}

				[].slice.call( document.querySelectorAll( 'input.input__field' ) ).forEach( function( inputEl ) {
					// in case the input is already filled..
					if( inputEl.value.trim() !== '' ) {
						classie.add( inputEl.parentNode, 'input--filled' );
					}

					// events:
					inputEl.addEventListener( 'focus', onInputFocus );
					inputEl.addEventListener( 'blur', onInputBlur );
				} );

				function onInputFocus( ev ) {
					classie.add( ev.target.parentNode, 'input--filled' );
				}

				function onInputBlur( ev ) {
					if( ev.target.value.trim() === '' ) {
						classie.remove( ev.target.parentNode, 'input--filled' );
					}
				}
			})();
      </script>



<script src="<?=$this->tplMediaUrl('923', '/js/library/classie.js'); ?>" type="text/javascript"></script>




</body>
</html>


