<?php include "./common/templates/mapheader.phtml"; ?>

    <script type="text/javascript">

        var mapa1;
        var lokalizacja;
        var MY_MAPTYPE_ID = 'custom_style';
        var geocoder = new google.maps.Geocoder();

        function initialize() {
            <?php if(is_numeric($this->mapLat) && is_numeric($this->mapLng)) : ?>
            var mapLat = <?php echo $this->mapLat; ?>;
            var mapLng = <?php echo $this->mapLng; ?>;
            lokalizacja = new google.maps.LatLng(mapLat, mapLng);
            enableMap();
            <?php else : ?>
            var address = "<?php echo $this->detailsDataAddressStreet; ?> <?php echo $this->detailsDataAddressLocalNumber; ?> <?php echo $this->detailsDataAddressZipCode; ?> <?php echo $this->detailsDataAddressCity; ?>";
            geocoder.geocode({'address': address}, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    lokalizacja = new google.maps.LatLng(results[0].geometry.location.lat(), results[0].geometry.location.lng());
                    enableMap();
                } else {
                    $("#googleMap").html('<p class="about_factory">Nie można wyświetlic mapy.<br />Wskazana lokalizacja jest niepoprawna.</p>');
                }
            });
            <?php endif; ?>
        }

        function enableMap() {
            var isMobile = true;
            if (window.matchMedia) {
                isMobile = !window.matchMedia('(max-device-width: 600px)').matches;
            }
            var mapOptions = {                              // DEFINICJA PARAMETRÓW MAPY
                center: lokalizacja,                    // ustalenie środka mapy
                zoom:15,                                    // ustalenie stopnia przybliżenia

                panControl: false,                          // kontrolka kierunku mapy
                zoomControl: true,                          // kontrolka przyblizenia
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.SMALL
                },
                mapTypeControl: true,                       // kontrolka typu mapy
                scaleControl: true,                         // kontrolka widocznosci skali
                streetViewControl: false,                   // kontrolka streetView
                overviewMapControl: false,                  // kontrolka małej mapy w rogu


                scrollwheel: false, 						// wyłączenie scrolowania mapy

                draggable: isMobile,

                mapTypeId: MY_MAPTYPE_ID,
                mapTypeControlOptions: {
                    mapTypeIds: [google.maps.MapTypeId.ROADMAP, MY_MAPTYPE_ID]
                }
                //mapTypeId:google.maps.MapTypeId.ROADMAP   // typ mapy do wyświetlenia
            };

            mapa1 = new google.maps.Map(document.getElementById("googleMap"),mapOptions);

            var styleOpts = [
                {
                    "featureType": "water",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#e9e9e9"
                        },
                        {
                            "lightness": 17
                        }
                    ]
                },
                {
                    "featureType": "landscape",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#f5f5f5"
                        },
                        {
                            "lightness": 20
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "geometry.fill",
                    "stylers": [
                        {
                            "color": "#ffffff"
                        },
                        {
                            "lightness": 17
                        }
                    ]
                },
                {
                    "featureType": "road.highway",
                    "elementType": "geometry.stroke",
                    "stylers": [
                        {
                            "color": "#ffffff"
                        },
                        {
                            "lightness": 29
                        },
                        {
                            "weight": 0.2
                        }
                    ]
                },
                {
                    "featureType": "road.arterial",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#ffffff"
                        },
                        {
                            "lightness": 18
                        }
                    ]
                },
                {
                    "featureType": "road.local",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#ffffff"
                        },
                        {
                            "lightness": 16
                        }
                    ]
                },
                {
                    "featureType": "poi",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#f5f5f5"
                        },
                        {
                            "lightness": 21
                        }
                    ]
                },
                {
                    "featureType": "poi.park",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#dedede"
                        },
                        {
                            "lightness": 21
                        }
                    ]
                },
                {
                    "elementType": "labels.text.stroke",
                    "stylers": [
                        {
                            "visibility": "on"
                        },
                        {
                            "color": "#ffffff"
                        },
                        {
                            "lightness": 16
                        }
                    ]
                },
                {
                    "elementType": "labels.text.fill",
                    "stylers": [
                        {
                            "saturation": 36
                        },
                        {
                            "color": "#333333"
                        },
                        {
                            "lightness": 40
                        }
                    ]
                },
                {
                    "elementType": "labels.icon",
                    "stylers": [
                        {
                            "visibility": "off"
                        }
                    ]
                },
                {
                    "featureType": "transit",
                    "elementType": "geometry",
                    "stylers": [
                        {
                            "color": "#f2f2f2"
                        },
                        {
                            "lightness": 19
                        }
                    ]
                },
                {
                    "featureType": "administrative",
                    "elementType": "geometry.fill",
                    "stylers": [
                        {
                            "color": "#fefefe"
                        },
                        {
                            "lightness": 20
                        }
                    ]
                },
                {
                    "featureType": "administrative",
                    "elementType": "geometry.stroke",
                    "stylers": [
                        {
                            "color": "#fefefe"
                        },
                        {
                            "lightness": 17
                        },
                        {
                            "weight": 1.2
                        }
                    ]
                }
            ]

            var styledMapOptions = {
                name: 'Skala szarości'
            };
            var customMapType = new google.maps.StyledMapType(styleOpts, styledMapOptions);
            mapa1.mapTypes.set(MY_MAPTYPE_ID, customMapType);


            // DODATKOWE ELEMENTY NA MAPIE
            var iconBase = "<?=$this->tplMediaUrl('923', '/images/marker.png'); ?>";
            var marker = new google.maps.Marker({           // DODAWANIE MARKERA
                position: lokalizacja,
                map: mapa1,
                title: escape("<?php echo $this->mapSectionTitle; ?>"),
                draggable:false, // true                              // możliwość przenoszenia markera
                icon: iconBase
            });

            var infowindow = new google.maps.InfoWindow({   // DODANIE CHMURKI PRZY MARKERZE
                content: "<?php echo $this->businessCardTitle; ?>",
                escape: true
            });

            // EVENT LISTENERS
            google.maps.event.addListener(marker, 'click', function() { // DODANIE KLIKNIECIA NA MARKER
                infowindow.open(mapa1,marker);
            });

        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>

<?php include "./common/templates/mapfooter.phtml"; ?>